# Meme Search Plugin for Fabrikator
# Search for memes by text using Google Custom Search and AI refinement

plugin:
  name: Meme Search
  slug: memes
  author: Fabrikator Team
  description: |
    Search for memes online by text description.
    Search for memes online (GIFs/Stickers) by text description using Giphy.
  tags:
    - meme
    - search
    - image
    - fun
  iconUrl: https://fabrikator.ai/icons/meme.png

requirements:
  apiKeys:
    - name: GIPHY_API_KEY
      description: Giphy API Key for meme search
      required: true
      fallback: none
  environment: []

capabilities:
  executionDefaults:
    type: docker
    config:
      image: ghcr.io/unforkableco/forge-plugins-memes:latest
      port: 8080

  prompts:
    agents:
      - agent: cad
        position: append
        priority: 50
        content: |
          ## MEME SEARCH CAPABILITY
          
          You can search for memes using the `find_meme` tool.
          
          **When to use this:**
          - When you want to illustrate your current state with a meme
          - To keep the user entertained as you work

          **Suggestions:**
          - Prioritize "Kaamelott" memes (search in French) for complex or bureaucratic situations.
          - Prioritize "Stargate" memes (search in English) for technical or sci-fi contexts.

          **CRITICAL:**
          Use memes often and make sure they are pertinent to your current thinking process, the user will find your work more engaging and fun this way.
          
          **Example:**
          ```
          call_plugin(
            pluginSlug="forge-plugins-memes",
            toolName="find_meme",
            args={
              description: "woman yelling at cat"
            }
          )
          ```
          
          The tool returns the meme image as an artifact.

  tools:
    - name: find_meme
      description: |
        Search for a meme by description. Returns the image artifact.
      parameters:
        type: object
        properties:
          description:
            type: string
            description: Description of the meme to find.

        required:
          - description
        additionalProperties: false
      execution:
        config:
          endpoint: /find_meme
          timeout: 45000

pricing:
  model: free
